import = ["~/.config/alacritty/rose-pine.toml"]

[window]
startup_mode = "Maximized"
opacity = 0.82
decorations = "None"
option_as_alt = "OnlyLeft"
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 15
