import = ["~/.config/alacritty/duskfox.toml"]

[window]
startup_mode = "Maximized"
decorations = "None"
option_as_alt = "OnlyLeft"
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 19.5

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"
