import = ["~/.config/alacritty/rose-pine.toml"]

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.75
blur = true
option_as_alt = "OnlyLeft"
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 17

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"
