import = ["~/.config/alacritty/carbonfox.toml"]

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.9
option_as_alt = "OnlyLeft"
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 18

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"
